### ISSUE TITLE
Landing page header does not actually inject elements into the page's <head>

### ISSUE THREAD

**Issue by ShenZhouHong** [johnhearfield/flarum-ext-landing-page#4]
This is just a minor bug, and nothing important - but the header section does not actually inject HTML tags into the actual `header` of the page. This could potentially mess up things such as `<meta>` tags.

**Comment by johnhearfield** [comment]
Since it was based off the IndexPage originally, it actually means the header of the page. Not the `<head></head>` of the HTML document
